homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 39.1422
  longitude: 117.1767
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    forecast: 24           #未来24小时天气，可有手工按需修改
    monitored_conditions:
      - temperature        #气温
      - precipitation      #雨量
      - windSpeed          #风速
      - pressure           #气压
      - windDirection      #风向
      - humidity           #湿度
  - platform: bitcoin
    display_options:
      - exchangerate
      - trade_volume_btc
  - platform: etherscan
    address: '0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359'
  #cpu
  ### cpu温度 ###
  - platform: command_line
    name: CPU_Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(2) }}'

  ### 系统状态 ###
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: memory_free

  ### 日出时间 ###
  - platform: template
    sensors:
      sunrise_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
        icon_template: mdi:weather-sunset-up


  ### 日落时间 ###
  - platform: template
    sensors:
      sunset_time:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
        icon_template: mdi:weather-sunset-down

  ########时间日期########
#  - platform: time_date
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat'

#测速
  - platform: speedtest
    minute: 30
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload


# Text to speech
tts:
  - platform: google
# camera这个配置项有三个值，分别对应三个摄像头；
# 每个摄像头又有各自不同的配置项和对应的值。
camera:
  - platform: mjpeg
    mjpeg_url: http://cdn-blog.oss-cn-beijing.aliyuncs.com/17-10-19/36125309.jpg
    name: camera1
# Cloud
cloud:

#媒体播放器
media_player :
  - platform: vlc
    name: vlc_player


device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200

mqtt:
  broker: m14.cloudmqtt.com
  port: 16833
  client_id: 888888
  keepalive: 60
  username: xdfggaoa
  password: qzEIbtGanCgm


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
